language: node_js
node_js:
  - '12'
  - '11'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run test
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: 1DCFdMc2kFMQA9p6aJ/XgofRCc+V0pIU2E3jx8jYM92sN/MLtbT59WVietQNOtZ4qtEh5Gr8+swrzx/xubZVe0YS0REaJWuQoQEjzJN6Gn6B/BoNz3fYulYn2LREb1CWbXkbTYLtSmUyKq/fPwy7DAbjvjJGgDnmZHrdRmWp8eLFBLLsurlfUNJSsWiS9EYt1pk+wVtMcHulfKSNELS0BG682pB0EX/X087XRrIxD+2ZEGGRHTE7bmTZNL7HIgdbAsePiMSJIC0ZEk8ST3nW2PQ5cl92GVQZxDZMvcgFn5dsabBGBlL/2RgBzOb8Az2/ooafOPIc1i1rwhZhEKZT6xPZfqSr7xPLODE0KpwpkH58V2oKrL08Xz0jSO8A6yXaxHd8WiIp0aHnfnID4Df5oMRJaUcy37ENOrSv3Vc7tKUfVTYeiNfV+HUcdI2AY2j8+lsyCi4eDcuRbQHRAQkjV7DPC3ddUEojDBgrUkffZ0ESY5fSHtUsUO1Gvh6wJ29AmY/oFp13e+Gj+3bjn11lZZ65L3aRZCnHp1vEW6/yeP+d7rHC5dvKg+eV0DSFrYBbLg4W5jn/QXeVEemc3uXgBHrjyd6Hu4pJ4Tw4Z4doHSlurtT62he4Xw2FZSPZxkvWhnl0FMjG/z6jTeoETzAWZPbtsSssMR5OeAUpQbKcr/k=
  on:
    tags: true
    branch: master
    node: 12
env:
  global:
    - secure: Ugcvy60xS+L/aan1zFoJDrgpsYEQcc+1hZce8nXon19FrbKymooXVlvrkAy0sRxrcsNBUpTG6jIKikAxsHAAsM/kP5J8WKV5Duu70RnAP+uMoJcgNnzJtu5qEAobxZ3VRCWfB4G+lDYkOxKqcob7wrkeGrEqrbC344BY0BrXHWcGk+gY/EiuWMDruDFZFPuksD7FV4y1h+qcCx5Yto1NhHJ3vZXIYpy2Kqrnkr/OKHg53N8S9R45eLzNFNse/h5ja2GzVrwVkBNNX2XnYXl/F61dnQ+v7UzInMJcBgifHleY7Ps3wKsc+gLEYJydhCZD/YAHdizdZFIxYjytFscHKrMMozbkCdOVzsBfN0i0LzOrVDhrX1lpfJ0Yh/Ly0oI7AZg+C87IMWNeg/vTsqhUIcIi61TWoAIx8J+RW7DrMSEs5rrTDipHwRez1zrG6hJBj8WSSYa+mC2rk2HcPa1Jv+jod+/uk3/F2Bdck1vaiW2gIluSAlWwMJq6cOMlJJwlhQArZMYg4hgYUpJ5x1oYMOIX+pNukCDufRkepDo5ASfx5rIyWEi4cgVnjmXGZlyRi1+Mus2YqB7GQ4air2nj0CUuDg5CTcZ4KYHpDBARDxKnZMTqCm9n4WN2w59eniHJIUTyD8F0jue9V76foI3z0KUg+hWOgyIlCejN8lYUGUQ=
notifications:
  slack:
    rooms:
      - secure: MeMFT9uhC2UdzZaEjXiloK/yHRlB2Q5k5/gPbxmJim09v7bzu0dEdusNpWuwbZJY13KXF+pXh1UPa1ICuI/GogQ7+waUldsTE7qCWDxyOAPsZIffPvJLlX4Xnkcod/QaJL1xmb9lgqxMy1jUh0gI3qGmqQ5ZQpWTkQtlnoSoQvJd3FqA1MqVl2WvzUq4ok6rAfM29oX1oVGY3Eo/pvaCms0EyL5HZzYSTYe3mUt1lagT7W2pg9IaEyf1rgHIoReoIsL9RRsu2Luj1XJd4rR1+kR3G3ndmcs5s6XtJK+XpworMEwDjSb1y+gl2FQAhwzqvGW+A7k2u7smENtp9r8qr42T7hVB5hRj4IVnuV3VRG/TLGtQ5YTdMKzV4+IUOfXlZtKKTKxhTG36E1nlSaXs9HQcHwbCguPjYf2wDdDoe5GcaJubStCWVCVgBATg5/A7dUfbTaFfxksVNPNy7yID9n04L8N0kyHljaWOs6VHLnIoTNWRRRitsRBaydwMtIZB6ikijSwqp1WSwKvB8mHCpktB4IWLhhURRtIVY7SP/efHXwIMSM25izOKmRneLIJjiTGxNSAgWvmOTWYAgVEofsXGHEvgQPIqAx177cHv6oWJHS4WpxJACsXarMzwDzHeEbfUPelOc6Vae+zuphtnbsjHfp+pePuZk0w1NEDVJwc=
    on_success: never
    on_failure: always
    on_pull_requests: false
